version: '3.8'

services:
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"  # Puerto para acceder a la interfaz web
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  # Permite a Portainer gestionar Docker
      - portainer_data:/data  # Persistencia de datos

volumes:
  portainer_data:
